version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: messmini-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: messmini
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - messmini-network

volumes:
  mysql_data:

networks:
  messmini-network:
    driver: bridge 